/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type AuthorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'author'
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type BlogPost = {
  _id: string
  _type: 'blogPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  excerpt?: string
  body?: RichText
  cover?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  author?: AuthorReference
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  publishedAt?: string
  updatedAt?: string
  featured?: boolean
  canonicalUrl?: string
  seo?: Seo
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  noIndex?: boolean
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
      _type: 'image'
      _key: string
    }
  | {
      language?: string
      filename?: string
      code?: string
      _type: 'codeBlock'
      _key: string
    }
>

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  role?: string
  avatar?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bio?: string
  socials?: Array<
    {
      _key: string
    } & Link
  >
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  intro?: string
  body?: RichText
  seo?: Seo
}

export type TrackRecordItem = {
  _id: string
  _type: 'trackRecordItem'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  body?: string
  client?: string
  order?: number
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  url?: string
  href?: string
  tagline?: string
  body?: string
  detail?: string
  kind?: 'own' | 'client'
  clientName?: string
  clientRole?: string
  clientApproved?: boolean
  scope?: Array<{
    label?: string
    value?: string
    _key: string
  }>
  tags?: Array<string>
  order?: number
  seo?: Seo
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  quote?: string
  name?: string
  role?: string
  company?: string
  source?: string
  sourceUrl?: string
  permissionGranted?: boolean
  order?: number
}

export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question?: string
  answer?: string
  order?: number
}

export type EngagementStep = {
  _id: string
  _type: 'engagementStep'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  meta?: string
  body?: string
  order?: number
}

export type Situation = {
  _id: string
  _type: 'situation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  body?: string
  order?: number
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  body?: string
  tags?: Array<string>
  order?: number
  seo?: Seo
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  tagline?: string
  email?: string
  phoneDisplay?: string
  phoneHref?: string
  location?: string
  locationNote?: string
  bookingLabel?: string
  bookingHref?: string
  socials?: Array<
    {
      _key: string
    } & Link
  >
  defaultSeo?: Seo
}

export type NumberedItem = {
  _type: 'numberedItem'
  title?: string
  body?: string
}

export type Metric = {
  _type: 'metric'
  value?: string
  label?: string
  source?: string
  verified?: boolean
}

export type Link = {
  _type: 'link'
  label?: string
  linkType?: 'internal' | 'external'
  internalPath?: string
  externalUrl?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AuthorReference
  | CategoryReference
  | BlogPost
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | RichText
  | Slug
  | Category
  | Author
  | Page
  | TrackRecordItem
  | Product
  | Testimonial
  | Faq
  | EngagementStep
  | Situation
  | Service
  | SiteSettings
  | NumberedItem
  | Metric
  | Link
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/sanity/queries.ts
// Variable: SITUATIONS_QUERY
// Query: *[_type == "situation"] | order(order asc){ _id, title, body }
export type SITUATIONS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  body: string | null
}>

// Source: src/sanity/queries.ts
// Variable: CAPABILITIES_QUERY
// Query: *[_type == "service"] | order(order asc){ _id, title, body, tags }
export type CAPABILITIES_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  body: string | null
  tags: Array<string> | null
}>

// Source: src/sanity/queries.ts
// Variable: ENGAGEMENT_QUERY
// Query: {  "steps": *[_type == "engagementStep"] | order(order asc){ _id, title, meta, body }}
export type ENGAGEMENT_QUERY_RESULT = {
  steps: Array<{
    _id: string
    title: string | null
    meta: string | null
    body: string | null
  }>
}

// Source: src/sanity/queries.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type == "product" && (kind != "client" || clientApproved == true)] | order(order asc){    _id, name, url, href, tagline, body, detail, kind, clientName, clientRole,    scope[]{ _key, label, value },    tags  }
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  url: string | null
  href: string | null
  tagline: string | null
  body: string | null
  detail: string | null
  kind: 'client' | 'own' | null
  clientName: string | null
  clientRole: string | null
  scope: Array<{
    _key: string
    label: string | null
    value: string | null
  }> | null
  tags: Array<string> | null
}>

// Source: src/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && permissionGranted == true] | order(order asc){    _id, quote, name, role, company, source  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string
  quote: string | null
  name: string | null
  role: string | null
  company: string | null
  source: string | null
}>

// Source: src/sanity/queries.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(order asc){ _id, question, answer }
export type FAQS_QUERY_RESULT = Array<{
  _id: string
  question: string | null
  answer: string | null
}>

// Source: src/sanity/queries.ts
// Variable: TRACK_RECORD_QUERY
// Query: *[_type == "trackRecordItem"] | order(order asc){ _id, title, body }
export type TRACK_RECORD_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  body: string | null
}>

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "situation"] | order(order asc){ _id, title, body }': SITUATIONS_QUERY_RESULT
    '*[_type == "service"] | order(order asc){ _id, title, body, tags }': CAPABILITIES_QUERY_RESULT
    '{\n  "steps": *[_type == "engagementStep"] | order(order asc){ _id, title, meta, body }\n}': ENGAGEMENT_QUERY_RESULT
    '\n  *[_type == "product" && (kind != "client" || clientApproved == true)] | order(order asc){\n    _id, name, url, href, tagline, body, detail, kind, clientName, clientRole,\n    scope[]{ _key, label, value },\n    tags\n  }\n': PRODUCTS_QUERY_RESULT
    '\n  *[_type == "testimonial" && permissionGranted == true] | order(order asc){\n    _id, quote, name, role, company, source\n  }\n': TESTIMONIALS_QUERY_RESULT
    '*[_type == "faq"] | order(order asc){ _id, question, answer }': FAQS_QUERY_RESULT
    '*[_type == "trackRecordItem"] | order(order asc){ _id, title, body }': TRACK_RECORD_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
